# action.yml
name: "Publish Terraform Module"
description: "it pusblishes a private terraform module withoout VCS"
inputs:
  organization: # id of input
    description: "Terraform organization name"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.organization }}
    - ${{ inputs.secret.TERRAFORM_CLOUD_TOKEN}}
